/**
 * PowerLab - SPICE / LTspice / ngspice Netlist Generator (.cir)
 * Generates accurate, runnable SPICE simulation decks with real semiconductor models,
 * snubber networks, gate drive timings, and Fourier directives.
 */

import {
  TopologyId,
  GridParams,
  SemiconductorParams,
  LoadParams,
  ConverterControls,
} from '../types/powerTypes';

export function generateSpiceNetlist(
  topology: TopologyId,
  grid: GridParams,
  semi: SemiconductorParams,
  load: LoadParams,
  controls: ConverterControls
): string {
  const Vpeak = (Math.SQRT2 * grid.vRms).toFixed(2);
  const freq = grid.frequency;
  const period = 1 / freq;
  const alphaDeg = controls.firingAngleAlpha;
  const delaySec = ((alphaDeg / 360) * period).toFixed(6);
  const pulseWidth = (period / 10).toFixed(6);

  const lines: string[] = [];

  lines.push(`* =========================================================================`);
  lines.push(`* PowerLab Simulation Deck - SPICE Netlist (.cir)`);
  lines.push(`* Topology: ${topology}`);
  lines.push(`* Generated by PowerLab Computational Physics Kernel`);
  lines.push(`* Grid: ${grid.vRms}V RMS @ ${grid.frequency}Hz | Firing Angle Alpha: ${alphaDeg}°`);
  lines.push(`* =========================================================================\n`);

  lines.push(`* --- GRID & LINE PARAMETERS ---`);
  if (topology.startsWith('3P') || topology === 'DUAL_CONVERTER_4Q') {
    const tB = (period / 3).toFixed(6);
    const tC = ((2 * period) / 3).toFixed(6);
    lines.push(`V_GRID_A 101 0 SIN(0 ${Vpeak} ${freq} 0 0 0)`);
    lines.push(`V_GRID_B 102 0 SIN(0 ${Vpeak} ${freq} ${tB} 0 0)`);
    lines.push(`V_GRID_C 103 0 SIN(0 ${Vpeak} ${freq} ${tC} 0 0)`);
    lines.push(`L_SA 101 1 ${grid.sourceInductanceLs.toExponential(3)} Rser=${grid.sourceResistanceRs}`);
    lines.push(`L_SB 102 2 ${grid.sourceInductanceLs.toExponential(3)} Rser=${grid.sourceResistanceRs}`);
    lines.push(`L_SC 103 3 ${grid.sourceInductanceLs.toExponential(3)} Rser=${grid.sourceResistanceRs}`);
  } else {
    lines.push(`V_GRID 101 0 SIN(0 ${Vpeak} ${freq} 0 0 0)`);
    lines.push(`L_S 101 1 ${grid.sourceInductanceLs.toExponential(3)} Rser=${grid.sourceResistanceRs}`);
    lines.push(`R_GND_REF 101 0 100MEG`);
  }

  lines.push(`\n* --- CONVERTER BRIDGE SEMICONDUCTOR SWITCHES ---`);
  if (topology === '1P_HALF_WAVE') {
    lines.push(`X_T1 1 10 G1 0 SCR_MACRO`);
    lines.push(`* Gate Trigger Pulse`);
    lines.push(`V_G1 G1 0 PULSE(0 10 ${delaySec} 1u 1u ${pulseWidth} ${period.toFixed(6)})`);
  } else if (topology === '1P_FULL_BRIDGE_SCR') {
    const delay2Sec = (((alphaDeg + 180) / 360) * period).toFixed(6);
    lines.push(`X_T1 1 10 G1 0 SCR_MACRO`);
    lines.push(`X_T2 0 11 G1 0 SCR_MACRO`);
    lines.push(`X_T3 0 10 G2 0 SCR_MACRO`);
    lines.push(`X_T4 1 11 G2 0 SCR_MACRO`);
    lines.push(`V_G1 G1 0 PULSE(0 10 ${delaySec} 1u 1u ${pulseWidth} ${period.toFixed(6)})`);
    lines.push(`V_G2 G2 0 PULSE(0 10 ${delay2Sec} 1u 1u ${pulseWidth} ${period.toFixed(6)})`);
  } else if (topology === '1P_FULL_BRIDGE_DIODE') {
    lines.push(`D1 1 10 DIODE_PWR`);
    lines.push(`D2 0 11 DIODE_PWR`);
    lines.push(`D3 0 10 DIODE_PWR`);
    lines.push(`D4 1 11 DIODE_PWR`);
  } else if (topology.startsWith('3P')) {
    lines.push(`* 3-Phase Bridge Thyristors`);
    lines.push(`X_T1 1 10 G1 0 SCR_MACRO`);
    lines.push(`X_T3 2 10 G3 0 SCR_MACRO`);
    lines.push(`X_T5 3 10 G5 0 SCR_MACRO`);
    lines.push(`X_T4 11 1 G4 0 SCR_MACRO`);
    lines.push(`X_T6 11 2 G6 0 SCR_MACRO`);
    lines.push(`X_T2 11 3 G2 0 SCR_MACRO`);
    lines.push(`* Firing Pulses (60° staggered)`);
    for (let k = 1; k <= 6; k++) {
      const pulseDelay = (((alphaDeg + (k - 1) * 60) / 360) * period).toFixed(6);
      lines.push(`V_G${k} G${k} 0 PULSE(0 10 ${pulseDelay} 1u 1u ${pulseWidth} ${period.toFixed(6)})`);
    }
  } else {
    // Generic bridge
    lines.push(`X_T1 1 10 G1 0 SCR_MACRO`);
    lines.push(`X_T2 0 11 G2 0 SCR_MACRO`);
    lines.push(`V_G1 G1 0 PULSE(0 10 ${delaySec} 1u 1u ${pulseWidth} ${period.toFixed(6)})`);
  }

  if (semi.enableSnubber) {
    lines.push(`\n* --- RC SNUBBER NETWORKS ---`);
    lines.push(`R_SNUB_1 1 10 ${semi.snubberRs}`);
    lines.push(`C_SNUB_1 10 10_S ${semi.snubberCs.toExponential(2)}`);
  }

  lines.push(`\n* --- LOAD IMPEDANCE & BACK-EMF ---`);
  lines.push(`R_LOAD 10 20 ${load.r}`);
  lines.push(`L_LOAD 20 21 ${load.l.toExponential(3)}`);
  lines.push(`V_EMF 21 11 DC ${load.e}`);
  if (load.type === 'RC' || load.type === 'RLC') {
    lines.push(`C_FILTER 10 11 ${load.c.toExponential(2)} IC=${load.e}`);
  }
  lines.push(`R_DC_GND 11 0 1MEG ; Floating reference`);

  lines.push(`\n* --- SEMICONDUCTOR SUBCIRCUIT MODELS ---`);
  lines.push(`.SUBCKT SCR_MACRO A K G GND_REF`);
  lines.push(`S_THY A K G GND_REF SW_THY`);
  lines.push(`D_FWD A K DIODE_PWR`);
  lines.push(`R_GATE G GND_REF 100`);
  lines.push(`.ENDS SCR_MACRO`);
  lines.push(
    `.MODEL DIODE_PWR D(IS=1e-9 RS=${semi.rd} BV=1200 IBV=1m TT=${semi.trr.toExponential(2)} VJ=${semi.vf0})`
  );
  lines.push(`.MODEL SW_THY VSWITCH(VON=2.5 VOFF=0.8 RON=${semi.rd} ROFF=1MEG)`);

  lines.push(`\n* --- ANALYSIS DIRECTIVES ---`);
  const tStop = (3 * period).toFixed(4);
  const tStart = (1 * period).toFixed(4);
  lines.push(`.TRAN 10u ${tStop} ${tStart} 5u`);
  lines.push(`.FOUR ${freq} V(10,11) I(R_LOAD)`);
  lines.push(`.PROBE V(10,11) I(R_LOAD) V(1) I(L_S)`);
  lines.push(`.END`);

  return lines.join('\n');
}
